// -*- mode: groovy -*-

// Licensed to the Apache Software Foundation (ASF) under one
// or more contributor license agreements.  See the NOTICE file
// distributed with this work for additional information
// regarding copyright ownership.  The ASF licenses this file
// to you under the Apache License, Version 2.0 (the
// "License"); you may not use this file except in compliance
// with the License.  You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

err = null

node('mxnetlinux-cpu') {
  // Loading the utilities requires a node context unfortunately
  checkout scm
  utils = load('ci/Jenkinsfile_utils.groovy')
}
utils.assign_node)labels(linux_gpu: 'mxnetlinux-gpu')


utils.main_wrapper(
core_logic: {
    stage('Flakiness Check'){
        node(NODE_LINUX_GPU) {
            ws('workspace/flakiness_check'){
                utils.init_git()
                utils.docker_run('ubuntu_cpu', 'select_tests', false)
                // only continue if some tests were selected
                if(fileExists('tests.tmp')){
                    utils.docker_run('ubuntu_build_cuda', 'build_ubuntu_gpu_cuda91_cudnn7', false)
                    utils.docker_run('ubuntu_gpu', 'run_flakiness_checker', false)
                }
            }
        }
    }
}
,
failure_handler: {
}
)
