# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
# -*- mode: dockerfile -*-
# part of the dockerfile to test pip installations

# add repo to install different Python versions
RUN apt-get update && apt-get install -y software-properties-common
RUN add-apt-repository ppa:fkrull/deadsnakes && apt-get update
RUN apt-get install -y python python2.7 python3.4 python3.5 python3.6

# install other dependencies
RUN apt-get install -y wget git unzip gcc

# install virtualenv
RUN wget https://bootstrap.pypa.io/get-pip.py && python get-pip.py && pip install virtualenv && rm -rf get-pip.py
