header:
  license:
    spdx-id: Apache-2.0
    copyright-owner: Apache Software Foundation

  paths-ignore:
    # Apache RAT License Checker Allowlist
    #
    # Version control
    - .github
    - .gitignore
    - .gitattributes
    - .gitmodules
    # The Apache MXNET (incubating) project contains subcomponents with separate
    # copyright notices and license terms. Your use of the source code for the
    # these subcomponents is subject to the terms and conditions of the following
    # licenses. If not stated otherwise, their copyright notices and license terms
    # are available at the path of the subcomponent.
    - 3rdparty
    - clipboard.js
    - coco.py
    # Licenses
    - licenses/*
    - LICENSE.binary.dependencies
    # Generated files during build
    - .buildinfo
    - Gemfile.lock
    - _build/*
    - _static/*
    - _site/*
    - _api/*
    - _includes/*
    - build/*
    - latex/*
    - target/*
    - site/*
    - xml/*
    - DartConfiguration.tcl
    - .*\.egg-info
    - .*\.t
    # Files generated by Cython
    - core.cpp
    - symbol.cpp
    - ndarray.cpp
    # Sphinx themes
    - themes/*
    # Binary or data files
    - .*\.ipynb
    - .*\.pyc
    - .*\.so
    - .*\.json
    - .*\.ref
    - .*\.txt
    - .*\.svg
    - .*\.lst
    - .*\.lds
    - .*\.in
    - .*\.diff
    - .*\.edl
    - .*\.md5
    - .*\.csv
    - .*\.log
    - .*\.interp
    - .*\.tokens
    - .*\.cPickle
    - .*\.names
    # Modules that are deleted prior to distribution
    - R-package/*
    # Specific files
    # Files that don't support comment
    - DISCLAIMER
    - MANIFEST
    - Changes
    - .codecov.yml
    - libmxnet.sym
    - libmxnet.ver
    # GitHub files
    - CODEOWNERS
    - .asf.yaml
    # Incorporated third-party source files that carry its own license, captured in licenses/
    - pool.h
    - pool.cuh
    - erfinv-inl.h
    - im2col.cuh
    - im2col.h
    - deformable_im2col.cuh
    - deformable_im2col.h
    - modulated_deformable_im2col.cuh
    - modulated_deformable_im2col.h
    - FindCUDAToolkit.cmake
    - FindJeMalloc.cmake
    - select_compute_arch.cmake

    # Incorporated third-party source files from Microsoft that carry Apache 2.0 license, captured in licenses/
    - deformable_psroi_pooling.cu
    - deformable_convolution.cu
    - deformable_convolution-inl.h
    - psroi_pooling.cc
    - multi_proposal.cu
    - deformable_psroi_pooling-inl.h
    - deformable_psroi_pooling.cc
    - deformable_convolution.cc
    - psroi_pooling.cu
    - multi_proposal.cc
    - multi_proposal-inl.h
    # Incorporated third-party source files from Microsoft that carry MIT license, captured in licenses/
    - modulated_deformable_convolution-inl.h
    - modulated_deformable_convolution.cc
    - modulated_deformable_convolution.cu
    # AL2 License header not at the beginning of the file
    - doap.rdf

  comment: on-failure
