#!/bin/bash

MXNET_ROOTDIR="$(pwd)"
MKLDNN_ROOTDIR="external/mkldnn"
MKLDNN_TMPDIR="$MKLDNN_ROOTDIR/tmp"
MKLDNN_SRCDIR="$MKLDNN_ROOTDIR/src"
MKLDNN_BUILDDIR="$MKLDNN_ROOTDIR/build"
MKLDNN_INSTALLDIR="$MKLDNN_ROOTDIR/install"
MKLDNN_COMMIT="$(cat ${MXNET_ROOTDIR}/mkldnn.commit)"
MKLDNN_CXX="g++"
MKLDNN_CC="gcc"

MKL_ROOTDIR="$MKLROOT"
MKLDNN_GITHUB="https://github.com/01org/mkl-dnn.git"
MKLDNN_CMAKE_FLAGS="$MKLDNN_SRCDIR -DCMAKE_INSTALL_PREFIX=$MKLDNN_INSTALLDIR -DMKLROOT=$MKL_ROOTDIR -B$MKLDNN_BUILDDIR -DCMAKE_CXX_COMPILER=$MKLDNN_CXX -DCMAKE_C_COMPILER=$MKLDNN_CC"
echo $MKLDNN_CMAKE_FLAGS
if [ ! -f "$MKLDNN_INSTALLDIR/lib/libmkldnn.so" ]; then
    git clone --no-checkout $MKLDNN_GITHUB $MKLDNN_TMPDIR
    rsync -a $MKLDNN_TMPDIR/ $MKLDNN_SRCDIR && rm -rf $MKLDNN_TMPDIR
    cd $MKLDNN_SRCDIR && git reset --hard $MKLDNN_COMMIT 
    cd $MXNET_ROOTDIR
    cmake $MKLDNN_CMAKE_FLAGS
    make -C $MKLDNN_BUILDDIR -j$(cat /proc/cpuinfo | grep processor | wc -l)
    make -C $MKLDNN_BUILDDIR install
fi


