# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.

name: mxnet
version: '1.5.0'
summary: MXNet is a deep learning framework designed for efficiency and flexibility.
description: |
  MXNet is a deep learning framework designed for both efficiency and 
  flexibility. It allows you to mix the flavours of symbolic programming and 
  imperative programming to maximize efficiency and productivity. In its core, 
  a dynamic dependency scheduler that automatically parallelizes both symbolic 
  and imperative operations on the fly. A graph optimization layer on top of 
  that makes symbolic execution fast and memory efficient. The library is 
  portable and lightweight, and it scales to multiple GPUs and multiple machines.

grade: stable
confinement: strict

apps:
  python:
    command: snap.python

parts:
  mxnet:
    source: .
    plugin: make
    build-packages:
      - build-essential
      - libatlas-base-dev
      - libopencv-dev
    stage-packages:
      - libatlas3-base
      - libopencv-calib3d2.4v5
      - libopencv-core2.4v5
      - libopencv-highgui2.4v5
      - libopencv-imgproc2.4v5
      - libopencv-ml2.4v5
      - libopencv-objdetect2.4v5
    prepare: |
      cp make/config.mk .
    build: |
      make
    install: |
      cp -r bin $SNAPCRAFT_PART_INSTALL/
      cp -r lib $SNAPCRAFT_PART_INSTALL/
    
  mxnet-ubuntu-python:
    plugin: python
    python-version: python2
    source: ./python
    stage-packages:
      - python-numpy
    python-packages:
      - graphviz
      - Jupyter
    after: [mxnet]
    
  python-wrapper:
    plugin: dump
    source: .
    stage:
      - snap.python
    prime:
      - snap.python

