// -*- mode: groovy -*-
// Jenkins pipeline
// See documents at https://jenkins.io/doc/book/pipeline/jenkinsfile/
// Runs nightly builds

stage("Hello World") {
  node('mxnetlinux') {
    sh "echo 'Hello World'"
  }
}