# -*- mode: dockerfile -*-
# dockerfile to build libmxnet.so for armv7
FROM dockcross/linux-armv7

ENV ARCH armv71
ENV CC /usr/bin/arm-linux-gnueabihf-gcc
ENV CXX /usr/bin/arm-linux-gnueabihf-g++

RUN apt-get update && \
    apt-get install -y libopenblas-dev:armhf && \
    rm -rf /var/lib/apt/lists/*

COPY install_functions.sh /work/
COPY build_functions.sh /work/
#WORKDIR /work/deps
WORKDIR /work/build
