FROM ubuntu:16.04
COPY install_functions.sh /work/
WORKDIR /work/deps
RUN /work/install_functions.sh ubuntu_install_all_deps
RUN /work/install_functions.sh ubuntu_install_mklml
COPY build_functions.sh /work/

WORKDIR /work/mxnet
ENV LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:/usr/local/lib
