FROM centos:7

ARG USER_ID=0

WORKDIR /work/deps

COPY install/centos7_core.sh /work/
RUN /work/centos7_core.sh
COPY install/centos7_python.sh /work/
RUN /work/centos7_python.sh
COPY install/centos7_adduser.sh /work/
RUN /work/centos7_adduser.sh 

ENV PYTHONPATH=./python/
WORKDIR /work/mxnet

COPY runtime_functions.sh /work/
