# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.

---
abstract: 'Perl interface to MXNet machine learning library'
author:
  - 'Sergey Kolychev <sergeykolychev.github@gmail.com>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: '6.30'
dynamic_config: 0
generated_by: 'ExtUtils::MakeMaker version 7.24, CPAN::Meta::Converter version 2.143240'
license: apache
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: AI-MXNet
no_index:
  directory:
    - t
    - inc
requires:
  AI::MXNetCAPI: '1.5'
  AI::NNVMCAPI: '1.4'
  Function::Parameters: '1.0705'
  Hash::Ordered: '0.012'
  GraphViz: '2.14'
  Mouse: v2.1.0
  PDL: '2.007'
  PDL::CCS: '1.23.4'
  Archive::Tar: '0'
  Digest::SHA: '0'
  HTTP::Tiny: '0'
  IO::Zlib: '0'
  JSON::PP: '0'
  parent: '0'
version: '1.5'
