scp /home/ubuntu/train/mxnet/libmxnet.a ubuntu@172.31.25.9:/home/ubuntu/train/mxnet/libmxnet.a
scp /home/ubuntu/train/mxnet/libmxnet.so ubuntu@172.31.25.9:/home/ubuntu/train/mxnet/libmxnet.so
scp /home/ubuntu/train/train_resnet.py ubuntu@172.31.25.9:/home/ubuntu/train/train_resnet.py
scp /home/ubuntu/train/parser/Program.cs ubuntu@172.31.25.9:/home/ubuntu/train/parser/Program.cs
scp /home/ubuntu/train/parser/project.json ubuntu@172.31.25.9:/home/ubuntu/train/parser/project.json
scp /home/ubuntu/train/mxnet/libmxnet.a ubuntu@172.31.41.154:/home/ubuntu/train/mxnet/libmxnet.a
scp /home/ubuntu/train/mxnet/libmxnet.so ubuntu@172.31.41.154:/home/ubuntu/train/mxnet/libmxnet.so
scp /home/ubuntu/train/train_resnet.py ubuntu@172.31.41.154:/home/ubuntu/train/train_resnet.py
scp /home/ubuntu/train/parser/Program.cs ubuntu@172.31.41.154:/home/ubuntu/train/parser/Program.cs
scp /home/ubuntu/train/parser/project.json ubuntu@172.31.41.154:/home/ubuntu/train/parser/project.json
scp /home/ubuntu/train/mxnet/libmxnet.a ubuntu@172.31.41.157:/home/ubuntu/train/mxnet/libmxnet.a
scp /home/ubuntu/train/mxnet/libmxnet.so ubuntu@172.31.41.157:/home/ubuntu/train/mxnet/libmxnet.so
scp /home/ubuntu/train/train_resnet.py ubuntu@172.31.41.157:/home/ubuntu/train/train_resnet.py
scp /home/ubuntu/train/parser/Program.cs ubuntu@172.31.41.157:/home/ubuntu/train/parser/Program.cs
scp /home/ubuntu/train/parser/project.json ubuntu@172.31.41.157:/home/ubuntu/train/parser/project.json
scp /home/ubuntu/train/mxnet/libmxnet.a ubuntu@172.31.41.156:/home/ubuntu/train/mxnet/libmxnet.a
scp /home/ubuntu/train/mxnet/libmxnet.so ubuntu@172.31.41.156:/home/ubuntu/train/mxnet/libmxnet.so
scp /home/ubuntu/train/train_resnet.py ubuntu@172.31.41.156:/home/ubuntu/train/train_resnet.py
scp /home/ubuntu/train/parser/Program.cs ubuntu@172.31.41.156:/home/ubuntu/train/parser/Program.cs
scp /home/ubuntu/train/parser/project.json ubuntu@172.31.41.156:/home/ubuntu/train/parser/project.json
scp /home/ubuntu/train/mxnet/libmxnet.a ubuntu@172.31.41.158:/home/ubuntu/train/mxnet/libmxnet.a
scp /home/ubuntu/train/mxnet/libmxnet.so ubuntu@172.31.41.158:/home/ubuntu/train/mxnet/libmxnet.so
scp /home/ubuntu/train/train_resnet.py ubuntu@172.31.41.158:/home/ubuntu/train/train_resnet.py
scp /home/ubuntu/train/parser/Program.cs ubuntu@172.31.41.158:/home/ubuntu/train/parser/Program.cs
scp /home/ubuntu/train/parser/project.json ubuntu@172.31.41.158:/home/ubuntu/train/parser/project.json
