FROM nvidia/cuda:7.5-cudnn5-devel
MAINTAINER Aran Khanna <arankhan@amazon.com>

# PYTHON2
RUN apt-get install -y python python-setuptools python-pip python-dev unzip gfortran
RUN pip install numpy nose scipy

# TESTDEPS
RUN apt-get install -y libgtest-dev cmake wget
RUN cd /usr/src/gtest && cmake CMakeLists.txt && make && cp *.a /usr/lib
RUN pip install nose cpplint 'pylint==1.4.4' 'astroid==1.3.6'

# TOOLCHAIN DEPS
RUN apt-get update && apt-get -y upgrade
RUN apt-get install -y install git bison cvs flex gperf texinfo automake libtool help2man make libtool-bin libncurses5-dev g++

# BUILD TOOLCHAIN
RUN git clone https://github.com/arank/crosstool-NG
RUN cd crosstool-NG
RUN make
RUN make install
RUN mkdir ../build
RUN cd ../build
RUN ct-ng arm-unknown-linux-gnueabi
RUN ct-ng build
