FROM ubuntu
MAINTAINER Aran Khanna <arankhan@amazon.com>

# UPDATE BOX
RUN apt-get update && apt-get -y upgrade

# TOOLCHAIN DEPS
RUN apt-get install -y python python-setuptools python-pip python-dev unzip gfortran
RUN apt-get install -y git bison cvs flex gperf texinfo automake libtool help2man make libtool-bin libncurses5-dev g++ cmake wget
RUN pip install numpy nose

# BUILD TOOLCHAIN
RUN git clone https://github.com/arank/crosstool-NG
RUN cd crosstool-NG && make && make install
RUN mkdir build && cd /build && ct-ng arm-unknown-linux-gnueabi && ct-ng build

