# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.

FROM ubuntu
MAINTAINER Aran Khanna <arankhan@amazon.com>

# UPDATE BOX
RUN apt-get update && apt-get -y upgrade

# TOOLCHAIN DEPS
RUN apt-get install -y python python-setuptools python-pip python-dev unzip gfortran
RUN apt-get install -y git bison cvs flex gperf texinfo automake libtool help2man make libtool-bin libncurses5-dev g++ cmake wget gawk
RUN pip install numpy nose

# BUILD TOOLCHAIN
RUN git clone https://github.com/arank/crosstool-NG
RUN cd crosstool-NG && ./bootstrap && ./configure && make && make install

RUN useradd -ms /bin/bash aran
RUN cd && cp -R .profile .bashrc /home/aran
ADD . /home/aran/build

RUN chown -R aran:aran /home/aran

RUN cd /home/aran/build && su -m aran -c "export HOME=/home/aran;ct-ng arm-unknown-linux-gnueabi;ct-ng build"

