FROM nvidia/cuda:7.5-cudnn5-devel

COPY install/ubuntu_install_core.sh /install/
RUN /install/ubuntu_install_core.sh
COPY install/ubuntu_install_python.sh /install/
RUN /install/ubuntu_install_python.sh
COPY install/ubuntu_install_scala.sh /install/
RUN /install/ubuntu_install_scala.sh
COPY install/ubuntu_install_r.sh /install/
RUN /install/ubuntu_install_r.sh
COPY install/ubuntu_install_perl.sh /install/
RUN /install/ubuntu_install_perl.sh
# Note: ln -s /dev/null /dev/raw1394 is to prevent error on python's
#   cv2 during import: "libdc1394 error: Failed to initialize libdc1394"
#   So, if you want to run another command, just update your CMD to start
#   with this script, followed by whatever you want. (Not cute, but works)
RUN ln /dev/null /dev/raw1394
