# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
FROM ubuntu
LABEL maintainer "arankhan@amazon.com"

# UPDATE BOX
RUN apt-get update && apt-get -y upgrade

# TOOLCHAIN DEPS
RUN apt-get install -y python python-setuptools python-pip python-dev unzip gfortran
RUN apt-get install -y git nodejs build-essential cmake

# BUILD EMSCRIPTEN
RUN git clone https://github.com/kripken/emscripten.git
RUN git clone https://github.com/kripken/emscripten-fastcomp
RUN cd emscripten-fastcomp && \
git clone https://github.com/kripken/emscripten-fastcomp-clang tools/clang && \
mkdir build && cd build && \
cmake .. -DCMAKE_BUILD_TYPE=Release -DLLVM_TARGETS_TO_BUILD="X86;JSBackend" \
-DLLVM_INCLUDE_EXAMPLES=OFF -DLLVM_INCLUDE_TESTS=OFF -DCLANG_INCLUDE_EXAMPLES=OFF \
-DCLANG_INCLUDE_TESTS=OFF && make
