FROM ubuntu:14.04

COPY install/ubuntu_*.sh /install/

RUN /install/ubuntu_install_core.sh
RUN /install/ubuntu_install_python.sh
RUN /install/ubuntu_install_scala.sh

RUN apt-get install -y doxygen
RUN pip install sphinx==1.3.5 CommonMark==0.5.4 breathe mock==1.0.1 recommonmark
