FROM amazonlinux
MAINTAINER Ly Nguyen <lynguyen@amazon.com>

COPY install/* /install/

RUN yum install -y git wget sudo

RUN chmod -R 755 install
RUN /install/install_opencv.sh
RUN /install/install_openblas.sh
RUN /install/install_python2.sh
RUN /install/install_python3.sh
RUN /install/install_testdeps.sh
RUN /install/install_julia.sh
RUN /install/install_maven.sh
RUN /install/install_library.sh

# Add MKLML library, compatiable with Ubuntu16.04
RUN wget --no-check-certificate -O /tmp/mklml.tgz https://github.com/01org/mkl-dnn/releases/download/v0.12/mklml_lnx_2018.0.1.20171227.tgz
RUN tar -zxvf /tmp/mklml.tgz && cp -rf mklml_*/* /usr/local/ && rm -rf mklml_*

ENV LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:/usr/local/lib
