

all:

include ../kaldi.mk

OBJFILES = ctypes.o

LIBNAME = kaldi-python-wrap

ADDLIBS = ../util/kaldi-util.a ../matrix/kaldi-matrix.a ../base/kaldi-base.a  ../hmm/kaldi-hmm.a ../cudamatrix/kaldi-cudamatrix.a ../nnet/kaldi-nnet.a ../thread/kaldi-thread.a

include ../makefiles/default_rules.mk
