import mxnet as mx
print("run CPU")
a = mx.nd.array([1, 2, 3, 4, 5], ctx=mx.cpu(0))
b = mx.nd.array([5, 4, 3, 2, 1], ctx=mx.cpu(0))
c = mx.nd.tvm_vector_add(a, b)
print("a =", a.asnumpy())
print("b =", b.asnumpy())
print("c =", c)
print("a + b =", c.asnumpy())

print("run bcast")
a = mx.nd.array([1, 2, 3, 4, 5], ctx=mx.cpu(0))
b = mx.nd.array([5, 4, 3, 2, 1], ctx=mx.cpu(0))
c = mx.nd.tvm_bcast_add(a, b)
print("a =", a.asnumpy())
print("b =", b.asnumpy())
print("a + b =", c.asnumpy())

print("run GPU")
a = mx.nd.array([1, 2, 3, 4, 5], ctx=mx.gpu(0))
b = mx.nd.array([5, 4, 3, 2, 1], ctx=mx.gpu(0))
c = mx.nd.tvm_vector_add(a, b)
print("a =", a.asnumpy())
print("b =", b.asnumpy())
print("c =", c)
print("a + b =", c.asnumpy())