/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_apache_mxnet_init_LibInfo */

#ifndef _Included_org_apache_mxnet_init_LibInfo
#define _Included_org_apache_mxnet_init_LibInfo
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_apache_mxnet_init_LibInfo
 * Method:    mxSymbolListAtomicSymbolCreators
 * Signature: (Lscala/collection/mutable/ListBuffer;)I
 */
JNIEXPORT jint JNICALL Java_org_apache_mxnet_init_LibInfo_mxSymbolListAtomicSymbolCreators
  (JNIEnv *, jobject, jobject);

/*
 * Class:     org_apache_mxnet_init_LibInfo
 * Method:    mxSymbolGetAtomicSymbolInfo
 * Signature: (JLorg/apache/mxnet/init/Base/RefString;Lorg/apache/mxnet/init/Base/RefString;Lorg/apache/mxnet/init/Base/RefInt;Lscala/collection/mutable/ListBuffer;Lscala/collection/mutable/ListBuffer;Lscala/collection/mutable/ListBuffer;Lorg/apache/mxnet/init/Base/RefString;)I
 */
JNIEXPORT jint JNICALL Java_org_apache_mxnet_init_LibInfo_mxSymbolGetAtomicSymbolInfo
  (JNIEnv *, jobject, jlong, jobject, jobject, jobject, jobject, jobject, jobject, jobject);

/*
 * Class:     org_apache_mxnet_init_LibInfo
 * Method:    mxListAllOpNames
 * Signature: (Lscala/collection/mutable/ListBuffer;)I
 */
JNIEXPORT jint JNICALL Java_org_apache_mxnet_init_LibInfo_mxListAllOpNames
  (JNIEnv *, jobject, jobject);

/*
 * Class:     org_apache_mxnet_init_LibInfo
 * Method:    nnGetOpHandle
 * Signature: (Ljava/lang/String;Lorg/apache/mxnet/init/Base/RefLong;)I
 */
JNIEXPORT jint JNICALL Java_org_apache_mxnet_init_LibInfo_nnGetOpHandle
  (JNIEnv *, jobject, jstring, jobject);

#ifdef __cplusplus
}
#endif
#endif
