# disable sudo to use container based build
sudo: false

# Use Build Matrix to do lint and build seperately
env:
  matrix:
    - TASK=lint LINT_LANG=cpp
    - TASK=doc
    - TASK=build CXX=g++

# dependent apt packages
addons:
  apt:
    packages:
      - doxygen
      - wget
      - unzip
      - libblas-dev
      - python3-pip

before_install:
  - git clone https://github.com/dmlc/dmlc-core
  - export TRAVIS=dmlc-core/scripts/travis
  - source ${TRAVIS}/travis_setup_env.sh

install:
  - pip3 install --upgrade pip --user
  - pip3 install  --user  cpplint pylint
  
script: scripts/travis_script.sh

before_cache:
  - ${TRAVIS}/travis_before_cache.sh

cache:
  directories:
    - ${HOME}/.cache/usr

notifications:
  email:
    on_success: change
    on_failure: always

