name: Clang format lint

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  clang-format:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
      - name: Fetch MxNet
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Run clang-format
        env:
          BASE_SHA: ${{ github.event.pull_request.base.sha }}
        run: |
          set -eu
          git remote add "${GITHUB_RUN_ID}" https://github.com/apache/incubator-mxnet.git
          git fetch "${GITHUB_RUN_ID}" "$GITHUB_BASE_REF"

          echo "~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~"
          echo "| clang-format failures found! Run: "
          echo "|    tool/lint/clang_format_ci.sh ${BASE_SHA} "
          echo "| to fix this error. "
          echo "| For more info, see: "
          echo "~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~"

          tools/lint/clang_format_ci.sh "${BASE_SHA}"

          GIT_DIFFERENCE=$(git diff)
          if [[ -z $GIT_DIFFERENCE ]]; then
            git remote remove "${GITHUB_RUN_ID}" # temporary remote is removed
            exit 0
          fi
          echo "$GIT_DIFFERENCE"
          git remote remove "${GITHUB_RUN_ID}" # temporary remote is removed
          exit 1
